apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: metrics-grafana-loadbalancer
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32264
    port: 80
    protocol: TCP
    targetPort: grafana
  selector:
    app.kubernetes.io/instance: metrics
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
