global:
  identity:
    auth:
      # Disable the Identity authentication
      # it will fall back to basic-auth: demo/demo as default user
      enabled: true
      publicIssuerUrl: "http://40.88.53.53/auth/realms/camunda-platform"
      operate.redirectUrl: "http://40.88.53.53/operate"
      operate.tasklistUrl: "http://40.88.53.53/tasklist"

identity:
  enabled: true
  keycloak:
    auth:
      adminUser: admin
      adminPassword: camunda
      managementUser: manager
      managementPassword: camunda
  env:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: "/identity"
    - name: IDENTITY_URL
      value: "http://40.88.53.53/identity"
    - name: KEYCLOAK_URL
      value: "http://40.88.53.53/auth"
  ingress:
    enabled: false

operate:
  enabled: true
  env:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: "/operate"
  ingress:
    enabled: false

tasklist:
  enabled: true
  env:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: "/tasklist"

optimize:
  enabled: false

prometheusServiceMonitor:
  enabled: false

zeebe:
  ingress:
    enabled: true

  clusterSize: 3
  partitionCount: 3
  replicationFactor: 3

  persistenceType: "disk"
  pvcStorageClassName: "ssd"
  pvcSize: "32Gi"

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

zeebe-gateway:
  replicas: 1

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  logLevel: ERROR

elasticsearch:
  enabled: true
  imageTag: 7.17.3
  replicas: 3
  minimumMasterNodes: 2
  # Allow no backup for single node setups
  # clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "ssd"
    resources:
      requests:
        storage: "30Gi"